### ISSUE TITLE
Encoding ISO 8859-1 not working on 1.17.0

### ISSUE THREAD

**Issue by jonassdp** [atom/encoding-selector#47] opened 2017-05-16 20:29 UTC
### Prerequisites

Atom 1.17.0 installed.

### Description

Chars like ç, ã, é, etc. are not getting encoded properly.

### Steps to Reproduce

1. Create a new file;
2. Change the encoding to ISO 8859-1;
3. Write "çãé" on it and save as "test.txt";
4. Close the file and open it again.

**Expected behavior:** Open the file with the properly encoding.

**Actual behavior:** Special characters get displayed as "���".

**Reproduces how often:** 100% of time.

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 3.4.3
git 2.9.2.windows.1
visual studio

### Additional Information
It started to happen as soon as I've updated to 1.17.0.

**Comment by 50Wliu** [comment] 2017-05-16 21:39
> Close the file and open it again.

If you manually change the encoding to ISO 8859-1 do the special characters get displayed properly?

**Comment by jonassdp** [comment] 2017-05-17 01:27
Nope. Even my old ISO encoded files aren't displayed properly.

**Comment by jonassdp** [comment] 2017-05-17 01:31
Actually you just need to save the file, immediately after save the characters get turned to �

**Comment by 50Wliu** [comment] 2017-05-17 15:40
It looks like this is a duplicate of #48, which has slightly more information.

**Closed by 50Wliu** 2017-05-17 15:40 UTC
Labels: needs-reproduction
